# -*- coding: utf-8 -*-
"""TagIt_Pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yNMdKLTNn2gMKBHuaSnPkk7lSrCLDUg
"""

!pip install -q transformers sentence-transformers tqdm pandas

import torch
print("GPU Available:", torch.cuda.is_available())

from transformers import pipeline
from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np
import torch
from tqdm import tqdm
import json
import os

# Configuration
MODEL_ID = "facebook/bart-large-mnli"
EMBED_MODEL = "all-MiniLM-L6-v2"
CONF_THRESHOLD = 0.6

device = 0 if torch.cuda.is_available() else -1

print("Loading Zero-Shot Model...")
classifier = pipeline("zero-shot-classification", model=MODEL_ID, device=device)

print("Loading Embedding Model...")
embedder = SentenceTransformer(EMBED_MODEL)

print("Setup Complete ✅")

# ---------------- Label Similarity Check ----------------
def check_label_similarity(labels):
    if len(labels) < 2:
        return

    embeddings = embedder.encode(labels, normalize_embeddings=True)
    similarity = np.dot(embeddings, embeddings.T)

    print("\n🔍 Label Similarity Check:")
    for i in range(len(labels)):
        for j in range(i+1, len(labels)):
            if similarity[i][j] > 0.8:
                print(f"⚠ {labels[i]} and {labels[j]} are very similar (score={similarity[i][j]:.2f})")

# ---------------- Single Text Classification ----------------
def classify_text(text, labels, threshold=CONF_THRESHOLD):
    result = classifier(text, labels)

    print("\n📊 Classification Results:")
    for l, s in zip(result['labels'], result['scores']):
        print(f"{l}: {s:.4f}")

    top_label = result['labels'][0]
    top_score = result['scores'][0]

    if top_score < threshold:
        print("\n⚠ Low confidence — Needs Review")
    else:
        print(f"\n✅ Final Prediction: {top_label} ({top_score:.4f})")

# ---------------- Batch Classification ----------------
def batch_classify(file_path, labels, output_file="results.csv", threshold=CONF_THRESHOLD):

    if not os.path.exists(file_path):
        print("File not found!")
        return

    with open(file_path, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    results = []

    print("\n🚀 Running Batch Classification...")
    for text in tqdm(lines):
        result = classifier(text, labels)
        top_label = result['labels'][0]
        top_score = result['scores'][0]

        results.append({
            "text": text,
            "top_label": top_label,
            "confidence": top_score,
            "needs_review": top_score < threshold,
            "all_scores": json.dumps(dict(zip(result['labels'], result['scores'])))
        })

    df = pd.DataFrame(results)
    df.to_csv(output_file, index=False)

    print(f"\n✅ Batch results saved to {output_file}")

    # Summary Analytics
    print("\n📈 Summary Analytics:")
    print("\nTop Label Counts:")
    print(df["top_label"].value_counts())

    print(f"\nAverage Confidence: {df['confidence'].mean():.4f}")
    print(f"Total Low-Confidence Cases: {df['needs_review'].sum()}")

text = "The product stopped working after two days and I want a refund."
labels = ["bug", "complaint", "praise", "question"]

check_label_similarity(labels)
classify_text(text, labels)

sample_texts = [
    "The delivery was fast and excellent service!",
    "I cannot log into my account.",
    "Please add dark mode to the app.",
    "Worst experience ever.",
    "How can I reset my password?"
]

with open("sample.txt", "w") as f:
    for line in sample_texts:
        f.write(line + "\n")

print("Sample file created ✅")

batch_classify("sample.txt",
               ["praise", "bug", "feature request", "complaint", "question"])

!pip install gradio transformers torch --quiet

import gradio as gr
from transformers import pipeline
import pandas as pd
import os

# Load zero-shot classification model
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

CONF_THRESHOLD = 0.5

# -----------------------------
# Single Text Classification
# -----------------------------
def classify_text(text, labels_input, threshold):
    if not text.strip():
        return "Please enter some text."

    labels = [label.strip() for label in labels_input.split(",") if label.strip()]

    if len(labels) < 2:
        return "Please provide at least two labels separated by commas."

    result = classifier(text, labels)

    output = ""
    for label, score in zip(result["labels"], result["scores"]):
        status = "⚠️ Needs Review" if score < threshold else ""
        output += f"{label} → {score:.4f} {status}\n"

    return output


# -----------------------------
# Batch Classification
# -----------------------------
def batch_classify(file_obj, labels_input, threshold):
    if file_obj is None:
        return "Please upload a .txt file."

    labels = [label.strip() for label in labels_input.split(",") if label.strip()]

    if len(labels) < 2:
        return "Please provide at least two labels separated by commas."

    results = []

    with open(file_obj.name, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for line in lines:
        text = line.strip()
        if text:
            result = classifier(text, labels)
            top_label = result["labels"][0]
            top_score = result["scores"][0]
            review_flag = "Needs Review" if top_score < threshold else "OK"

            results.append([text, top_label, round(top_score, 4), review_flag])

    df = pd.DataFrame(results, columns=["Text", "Predicted Label", "Confidence", "Status"])

    output_file = "batch_results.csv"
    df.to_csv(output_file, index=False)

    return df


# -----------------------------
# Gradio Interface
# -----------------------------
with gr.Blocks() as demo:
    gr.Markdown("# 🧠 TagIt Pro - Zero-Shot Text Classifier")

    with gr.Tab("Single Text Mode"):
        text_input = gr.Textbox(label="Enter Text")
        labels_input = gr.Textbox(label="Enter Labels (comma separated)")
        threshold_slider = gr.Slider(0, 1, value=0.5, label="Confidence Threshold")
        output_box = gr.Textbox(label="Classification Results")
        classify_btn = gr.Button("Classify")

        classify_btn.click(
            classify_text,
            inputs=[text_input, labels_input, threshold_slider],
            outputs=output_box
        )

    with gr.Tab("Batch Mode"):
        file_input = gr.File(label="Upload .txt File")
        batch_labels_input = gr.Textbox(label="Enter Labels (comma separated)")
        batch_threshold_slider = gr.Slider(0, 1, value=0.5, label="Confidence Threshold")
        batch_output = gr.Dataframe(label="Batch Results")
        batch_btn = gr.Button("Run Batch Classification")

        batch_btn.click(
            batch_classify,
            inputs=[file_input, batch_labels_input, batch_threshold_slider],
            outputs=batch_output
        )

demo.launch(share=True)